### ISSUE TITLE
Crash on default value missing

### ISSUE THREAD

**Issue by antheas** [hhd-dev/hhd-ui#2] opened 2024-01-14 23:36 UTC
Default values on hhd are optional. Right now, if a default value is missing, hhd-ui crashes.

Uncomment the display plugin to debug.

**Comment by aarron-lee** [comment] 2024-01-15 04:19
@antheas the problem is not the default value, the problem is that the value is `null`, which crashes the component.

the value was missing, not `defaultValue`. Pushed a fix/workaround to make the regular value optional

**Closed by aarron-lee** 2024-01-15 04:19 UTC
